# Generated by Django 3.2.9 on 2021-12-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComCategory',
            fields=[
                ('COM_CATEGORY_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('COM_CATEGORY_NAME', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'TBL_COM_CATEGORY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('COMMENT_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('COMMENT_CONTENT', models.TextField()),
                ('COMMENT_WRITE_DATE', models.DateTimeField()),
                ('COMMENT_UPDATE_DATE', models.DateTimeField()),
                ('PARENT_COMMENT_ID', models.IntegerField(null=True)),
                ('USER_ID', models.CharField(max_length=20)),
                ('POST_ID', models.IntegerField()),
            ],
            options={
                'db_table': 'TBL_COMMENT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('LIKE_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('LIKE_STATE', models.CharField(max_length=1)),
                ('USER_ID', models.CharField(max_length=20)),
                ('POST_ID', models.IntegerField()),
            ],
            options={
                'db_table': 'TBL_LIKE',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerCategory',
            fields=[
                ('PER_CATEGORY_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('PER_CATEGORY_NAME', models.CharField(max_length=30)),
                ('PARENT_PER_CATEGORY_ID', models.IntegerField(null=True)),
                ('USER_ID', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'TBL_PER_CATEGORY',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('POST_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('POST_TITLE', models.CharField(max_length=100)),
                ('POST_CONTENT', models.TextField()),
                ('POST_WRITE_DATE', models.DateTimeField()),
                ('POST_UPDATE_DATE', models.DateTimeField()),
                ('USER_ID', models.CharField(max_length=20)),
                ('COM_CATEGORY_ID', models.CharField(max_length=10)),
                ('PER_CATEGORY_ID', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'TBL_POST',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('USER_ID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('USER_PWD', models.CharField(max_length=20)),
                ('USER_NAME', models.CharField(max_length=30)),
                ('USER_GENDER', models.CharField(max_length=1)),
                ('USER_BIRTH', models.DateField()),
                ('USER_EMAIL', models.CharField(max_length=50, null=True)),
                ('USER_TEL', models.CharField(max_length=11, null=True)),
            ],
            options={
                'db_table': 'TBL_USER',
                'managed': True,
            },
        ),
    ]
